### ISSUE TITLE
Clarification: Is this project being actively maintained or has it been abandoned?

### ISSUE THREAD

**Issue by johannsa** [MapsterMapper/Mapster#403]
Hi all!

Perhaps some senior contributor can give some clarification.

Given these facts:

- The [last release](https://github.com/MapsterMapper/Mapster/releases/tag/7.2.0) was on APR2021;
- The [last PR merged](https://github.com/MapsterMapper/Mapster/pull/334) was in MAY2021;
- The [last commit](https://github.com/MapsterMapper/Mapster/commit/e50e3cf3648e3c8d1773ad91482675bc2f4e1ae4) was in JUN2021;
- The [main contributor/maintainer @chaowlert](https://github.com/chaowlert?tab=overview&from=2021-06-01&to=2021-06-30) has not been around since JUN2021;
    - Which in the current COVID-19 times is very worrying.
    - I hope he is doing fine.
- The release back in NOV2021 of .NET 6, the current .NET LTS version; and
- There are some PRs [[390]](https://github.com/MapsterMapper/Mapster/pull/390) [[397]](https://github.com/MapsterMapper/Mapster/pull/397) to fix Mapster for .NET 6 that haven't been reviewed/merged...

I wonder:
- Is this project being actively maintained or has it been abandoned?
    - If actively maintained: Do you need help?
    - If abandoned: Is there any successor or alternative recommendation?

Thanks beforehand!

**Comment by eswann** [comment]
Hey @johannsa and others, I also added this comment to the PR for .net 6 support. 
I merged the PR, but it's been years since I've contributed to this project, and I haven't worked in the .Net space in a few years as well. As well, @chaowlert basically rewrote the entire project over time after I passed it off to him. I'm not sure what build procedures @chaowlert has been using to publish these packages out to Nuget and currently I don't have the bandwidth to figure it out.
Agreed that it looks like @chaowlert has gone dark for several months now, which is very troubling because I know he took a lot of pride in this project, so I only hope that his health is OK. I would be happy to try to set up somebody else to do the necessary work if anyone would like to volunteer.

**Comment by FariborzRazban** [comment]
is the issue for dotnet 6 resolved? i'm still having the same problem :(

**Comment by andrerav** [comment]
@eswann I haven't made any contributions to this project previously, but I'd be happy to help out to ensure that it stays active. I already maintain a few open source projects (NHibernate.Spatial as well as some pet projects) as well as their corresponding packages on NuGet.

**Comment by FariborzRazban** [comment]
@eswann I'd like to help as well but I have zero experience with open source projects however, I'm dotnet dev for more than 10 years now so, i'm looking for some trouble if you guys would have me

**Comment by eswann** [comment]
Thanks @andrerav! I'll add you into the org and see what i can do to add you into the nuget account.

**Comment by andrerav** [comment]
@eswann Great, thank you, I have accepted the invitation. My nuget username is the same as my GitHub username, i.e [andrerav](https://www.nuget.org/profiles/andrerav).

**Comment by eswann** [comment]
@andrerav You now have access to the Nuget package for Mapster. I don't have access to the ancillary packages. We'd have to ask @chaowlert to add you to those.

**Comment by FariborzRazban** [comment]
> @FariborzRazban I have added you to the project as well! If you have a nuget username, please provide it to me.

I think you can find me on nugget with this: Razban
